apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: mlrun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:3
          ports:
            - containerPort: 5000
          env:
            - name: REGISTRY_AUTH
              value: htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry Realm"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /auth/htpasswd
            - name: REGISTRY_HTTP_SECRET
              value: changeme-registry-secret
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
            - name: auth-volume
              mountPath: /auth
      volumes:
        - name: registry-storage
          hostPath:
            path: /home/johnny/swan/opt/registry
            type: DirectoryOrCreate
        - name: auth-volume
          secret:
            secretName: registry-auth
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: mlrun
spec:
  type: NodePort
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
