FROM dragon:30500/foulds/mlrun-torch-base:2.7.1

RUN pip install --upgrade pip \
 && pip install --no-cache-dir \
    numpy==1.26.4 \
    pandas==2.1.4 \
    flashinfer-python==0.2.10 \
     vllm==0.10.0 
